config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: "callbacks" }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
  devise_scope :user do
    get 'singup', to: 'devise/registrations#new'
  end
  resources :comments
  resources :friend_relationships
  resources :friend_requests
  resources :likes
  resources :posts
  resources :users
  root "posts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/friend_relationship.rb
class FriendRelationship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:github]
  has_many :posts
  has_many :likes
  has_many :comments
  has_many :sent_friend_requests, foreign_key: "sender_id", class_name: "FriendRequest"
  has_many :received_friend_requests, foreign_key: "receiver_id", class_name: "FriendRequest"
  has_many :friend_relationships
  has_many :friends, foreign_key: "friend_id", class_name: "FriendRelationship"
  has_one_attached :image

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.name = auth.info.name
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def email_required?
    false
  end
  
  def email_changed?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # Permit the `subscribe_newsletter` parameter along with the other
    # sign up parameters.
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = current_user.comments.build(comment_params)
    redirect_to posts_path if @comment.save
  end

  def update
    redirect_to posts_path if @comment.update(comment_params)
  end

  def destroy
    @comment.destroy
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:post_id, :user_id, :body)
    end
end

app/controllers/friend_relationships_controller.rb
class FriendRelationshipsController < ApplicationController

  def index
    @friend_relationships = FriendRelationship.where(user_id: current_user.id)
  end

  def new
    @friend_relationship = FriendRelationship.new
  end

  def create
    @friend_relationship_1 = FriendRelationship.new(user_id: friend_relationship_params[:user_id], friend_id: friend_relationship_params[:friend_id])
    @friend_relationship_2 = FriendRelationship.new(friend_id: friend_relationship_params[:user_id], user_id: friend_relationship_params[:friend_id])
    if @friend_relationship_1.save && @friend_relationship_2.save
      FriendRequest.find(friend_relationship_params[:friend_request_id]).destroy
      redirect_to users_path
    end
  end

  private
    def friend_relationship_params
      params.permit(:user_id, :friend_id, :friend_request_id, :authenticity_token, :commit)
    end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  def index
    @friend_requests = FriendRequest.where(receiver_id: current_user.id)
  end

  def new
    @friend_request = FriendRequest.new
  end

  def create
    @friend_request = FriendRequest.new(sender_id: friend_request_params[:sender_id], receiver_id: friend_request_params[:receiver_id])
    redirect_to users_path if @friend_request.save
  end

  def destroy
    FriendRequest.find(params[:id]).destroy
  end

  private
    def friend_request_params
      params.permit(:sender_id, :receiver_id, :authenticity_token, :commit)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @like = Like.new(post_id: like_params[:post_id], user_id: like_params[:user_id])
    redirect_to posts_path if @like.save
  end

  private
    def like_params
      params.permit(:post_id, :user_id, :authenticity_token, :commit)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    check_array = [current_user.id].concat(current_user.friends.map{ |u| u.user_id })
    @posts = Post.where(user_id: check_array).order("created_at DESC").limit(10)
    @likes_array = Like.where(user_id: current_user.id).map{ |u| u.post_id }
    @post = Post.new
    @comment = Comment.new
  end

  def show
    @comment = Comment.new
    @likes_array = Like.where(user_id: current_user.id).map{ |u| u.post_id }
  end

  def new
    @post = current_user.posts.build
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
    redirect_to root_path if @post.save
  end

  def update
    redirect_to @post if @post.update(post_params)
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:body, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super
    if @user.persisted? && !@user.email.empty?
      UserMailer.with(user: @user).welcome_email.deliver_later
    end
  end

  private
  def sign_up_params
    params.require(:user).permit( :name, :email, :password, :password_confirmation)
  end

  def sign_in_params
    params.require(:user).permit( :email, :password)
  end

  def account_update_params
    params.require(:user).permit( :name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit ]

  def index
    @users = User.where.not(id: current_user.id)
    @friend_request_array = current_user.sent_friend_requests.map{ |u| u.receiver_id }
    @friend_array = current_user.friends.map{ |u| u.user_id }
  end

  def show
    @posts = Post.where(user_id: params[:id]).order("created_at DESC")
    @post = Post.new
    @comment = Comment.new
    @likes_array = Like.where(user_id: current_user.id).map{ |u| u.post_id }
  end

  def edit
  end

  private
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_relationships_helper.rb
module FriendRelationshipsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friend_requests/_requestgrid.html.erb
<% @friend_requests.each do | friend_request | %>
  <div class="box">
    <article class="media">
      <div class="media-content">
        <div class="content">
          <strong><%= friend_request.sender.name %></strong><br/>
        </div>


        <nav class="level">
          <div class="level-left is-mobile">
            <div class="level-left is-mobile">
              <%= link_to friend_relationships_path(user_id: current_user.id, friend_id: friend_request.sender.id, friend_request_id: friend_request.id), method: :post, data: { confirm: "Approve friend request ?"
                } do %>
                  <span class="icon"><i class="fa fa-check" aria-hidden="true"></i></span>
                <% end %>
            </div>
          </div>
        </nav>



      </div>
    </article>
  </div>
<% end %>
        

app/views/friend_requests/index.html.erb
<section class="section">
  <div class="container">
    <div class="flex-grid-thirds">
      <%= render 'requestgrid' %>
    </div>
  </div>
</section>

app/views/posts/_commentform.html.erb
<%= simple_form_for(@comment) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :body, label: "Comment the post", input_html: { class: "text " }, wrapper: false, label_html: {class: "label"}, placeholder: "Write your comment", autofocus: false %>
    <%= f.hidden_field :post_id, value: post_id %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/posts/_feed.html.erb
<div class="column is-half">
  <% @posts.each do | post | %>
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure>
            <%= link_to post.user, class: "level-item" do %>
              <% if post.user.image.attached? %>
                <%= image_tag post.user.image.variant(resize: "64x64!"), class: "image" %>
              <% else %>
                  <%= image_tag("user.png", class: "image", size: "64x64",) %>
              <% end %>
            <% end %>
          </figure>
        </div>

        <div class="media-content">
          <div class="content">
            <strong><%= post.user.name %></strong><br/>
            <p><%= post.body %></p>
          </div>
          <nav class="level">
            <div class="level-left is-mobile">
                <%= link_to post, class: "level-item" do %>
                  <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                <% end %>
              <% if current_user == post.user %>

                <%= link_to edit_post_path(post), class: "level-item" do %>
                  <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                <% end %>

                <%= link_to post, method: :delete, data: { confirm: "Are you sure you want to delete this post?"
                } do %>
                  <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                <% end %>
                  
              <% elsif @likes_array.include?(post.id) %>
                <div class="notif-icon">
                  <span class="icon"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i></span>
                  <div class="like-txt"><%= Like.where(post_id: post.id).length %></div>
                </div>

              <% else %>
                <%= link_to likes_path(user_id: current_user.id, post_id: post.id), method: :post, data: { confirm: "Like this post?"
                    } do %>
                  <div class="notif-icon">
                    <span class="icon"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i></span>
                    <div class="like-txt"><%= Like.where(post_id: post.id).length %></div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </nav>

          <% post.comments.each do | comment | %>
            <div class="box">
              <strong><%= comment.user.name %></strong><br/>
              <p><%= comment.body %></p>
            </div>
          <% end %>

          <article class="media box">
            <div class="media-content">
              <%= render 'posts/commentform', post_id: post.id %>
            </div>
          </article>

        </div>
      </article>
    </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
  <article class="media box">
    <figure>
      <% if current_user.image.attached? %>
        <%= image_tag current_user.image.variant(resize: "64x64!"), class: "image" %>
      <% else %>
          <%= image_tag("user.png", class: "image", size: "64x64",) %>
      <% end %>
    </figure>
    <div class="media-content">
      <%= simple_form_for(@post) do |f| %>
      <%= f.error_notification %>
      <div class="field">
        <div class="control">
          <%= f.input :body, label: "Post about it", input_html: { class: "textarea " }, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new post...", autofocus: true %>
        </div>
      </div>
      <%= f.button :submit, class: "button is-info" %>
      <% end %>
    </div>
  </article>
  

app/views/posts/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Post</h1>
				<%= render 'form', post: @post %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', posts_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/posts/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <%= render 'form' %>
      <%= render 'feed' %>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-half">
 
        <div class="box">
          <article class="media">
            <div class="media-left">
              <figure>
                <%= link_to @post.user, class: "level-item" do %>
                  <% if @post.user.image.attached? %>
                    <%= image_tag @post.user.image.variant(resize: "64x64!"), class: "image" %>
                  <% else %>
                      <%= image_tag("user.png", class: "image", size: "64x64",) %>
                  <% end %>
                <% end %>
              </figure>
            </div>

            <div class="media-content">
              <div class="content">
                <strong><%= @post.user.name %></strong><br/>
                <p><%= @post.body %></p>
              </div>
              <nav class="level">
                <div class="level-left is-mobile">
                  <% if current_user == @post.user %>

                    <%= link_to edit_post_path(@post), class: "level-item" do %>
                      <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                    <% end %>

                    <%= link_to @post, method: :delete, data: { confirm: "Are you sure you want to delete this post?"
                    } do %>
                      <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                    <% end %>
                      
                  <% elsif @likes_array.include?(@post.id) %>
                    <div class="notif-icon">
                      <span class="icon"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i></span>
                      <div class="like-txt"><%= Like.where(post_id: @post.id).length %></div>
                    </div>

                  <% else %>
                    <%= link_to likes_path(user_id: current_user.id, post_id: @post.id), method: :post, data: { confirm: "Like this post?"
                        } do %>
                      <div class="notif-icon">
                        <span class="icon"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i></span>
                        <div class="like-txt"><%= Like.where(post_id: @post.id).length %></div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </nav>

              <% @post.comments.each do | comment | %>
                <div class="box">
                  <strong><%= comment.user.name %></strong><br/>
                  <p><%= comment.body %></p>
                </div>
              <% end %>

              <article class="media box">
                <div class="media-content">
                  <%= render 'posts/commentform', post_id: @post.id %>
                </div>
              </article>

            </div>
          </article>
        </div>
    </div>
    </div>
  </div>
</section>

app/views/users/_profile.html.erb
<div class="column is-half">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure>
						<% if @user.image.attached? %>
							<%= image_tag @user.image.variant(resize: "64x64!"), class: "image" %>
						<% else %>
								<%= image_tag("user.png", class: "image", size: "64x64",) %>
						<% end %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= @user.name %></strong><br />
							<small><%= @user.email %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Posts</p>
						<p class="title is-6"><%= @user.posts.count %></p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/users/_usergrid.html.erb
<% @users.each do | user | %>
  <div class="box">
    <article class="media">
      <div class="media-content">
        <div class="content">
          <strong><%= user.name %></strong><br/>
        </div>

        <nav class="level">
          <div class="level-left is-mobile">
            <div class="level-left is-mobile">
              <% if @friend_request_array.include?(user.id) %>
                <p>Friend request sent</p>
              <% elsif @friend_array.include?(user.id) %>
                <p>Friend</p>
              <% else %>
                <%= link_to friend_requests_path(sender_id: current_user.id, receiver_id: user.id), method: :post, data: { confirm: "Send friend request ?"
                } do %>
                  <span class="icon"><i class="fa fa-plus" aria-hidden="true"></i></span>
                <% end %>
              <% end %>
            </div>
          </div>
        </nav>

      </div>
    </article>
  </div>
<% end %>
        

app/views/users/index.html.erb
<section class="section">
  <div class="container">
    <div class="flex-grid-thirds">
      <%= render 'usergrid' %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <%= render 'users/profile' %>
      <%= render 'posts/feed' %>
    </div>
  </div>
</section>