config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: "callbacks" }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
  devise_scope :user do
    get 'singup', to: 'devise/registrations#new'
  end
  resources :comments
  resources :friend_relationships
  resources :friend_requests
  resources :likes
  resources :posts
  resources :users
  root "posts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/friend_relationship.rb
class FriendRelationship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:github]
  has_many :posts
  has_many :likes
  has_many :comments
  has_many :sent_friend_requests, foreign_key: "sender_id", class_name: "FriendRequest"
  has_many :received_friend_requests, foreign_key: "receiver_id", class_name: "FriendRequest"
  has_many :friend_relationships
  has_many :friends, foreign_key: "friend_id", class_name: "FriendRelationship"
  has_one_attached :image

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.name = auth.info.name
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def email_required?
    false
  end
  
  def email_changed?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # Permit the `subscribe_newsletter` parameter along with the other
    # sign up parameters.
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = current_user.comments.build(comment_params)
    redirect_to posts_path if @comment.save
  end

  def update
    redirect_to posts_path if @comment.update(comment_params)
  end

  def destroy
    @comment.destroy
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:post_id, :user_id, :body)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @like = Like.new(post_id: like_params[:post_id], user_id: like_params[:user_id])
    redirect_to posts_path if @like.save
  end

  private
    def like_params
      params.permit(:post_id, :user_id, :authenticity_token, :commit)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    check_array = [current_user.id].concat(current_user.friends.map{ |u| u.user_id })
    @posts = Post.where(user_id: check_array).order("created_at DESC").limit(10)
    @likes_array = Like.where(user_id: current_user.id).map{ |u| u.post_id }
    @post = Post.new
    @comment = Comment.new
  end

  def show
    @comment = Comment.new
    @likes_array = Like.where(user_id: current_user.id).map{ |u| u.post_id }
  end

  def new
    @post = current_user.posts.build
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
    redirect_to root_path if @post.save
  end

  def update
    redirect_to @post if @post.update(post_params)
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:body, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit ]

  def index
    @users = User.where.not(id: current_user.id)
    @friend_request_array = current_user.sent_friend_requests.map{ |u| u.receiver_id }
    @friend_array = current_user.friends.map{ |u| u.user_id }
  end

  def show
    @posts = Post.where(user_id: params[:id]).order("created_at DESC")
    @post = Post.new
    @comment = Comment.new
    @likes_array = Like.where(user_id: current_user.id).map{ |u| u.post_id }
  end

  def edit
  end

  private
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_relationships_helper.rb
module FriendRelationshipsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odinbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar is-info">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-5">Odinbook</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
        <div id="navbarExample" class="navbar-menu">
          <div class="navbar-end">
            <div class="field is-grouped">
              <% if user_signed_in? %>
                <p class="control">
                  <%= link_to 'New Post', root_path, class: "button is-info is-inverted" %>
                </p>
                <p class="control">
                  <%= link_to 'Friends', users_path, class: "button is-info is-inverted" %>
                </p>


                <%= link_to friend_requests_path do %>
                  <div class="notif-icon">
                    <span class="icon"><i class="fa fa-bell fa-2x" aria-hidden="true"></i></span>
                    <div class="notif-txt"><%= FriendRequest.where(receiver_id: current_user.id).length %></div>
                  </div>
                <% end %>


                <p class="control">
                  <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
                </p>
                <p>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-info" %>
                </p>
              <% else %>
              <p class="control">
                <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
              </p>
              <p class="control">
                <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
              </p>
              <% end %>
            </div>
          </div>
        </div>

    </nav>

    <%= yield %>
  </body>
</html>